In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print (arr + 2)
print(arr*3)
print(arr/2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Reversed array: [5 4 6 3 2 1]


In [8]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)
most_frequent_value = values[np.argmax(counts)]

indices = np.where(x == most_frequent_value)[0]

print("Most frequent value in x:", most_frequent_value)
print("Indices of most frequent value in x:", indices)

Most frequent value in x: 1
Indices of most frequent value in x: [0 5 7 8 9]


In [7]:
import numpy as np
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values_y, counts_y = np.unique(y, return_counts=True)
most_frequent_value_y = values_y[np.argmax(counts_y)]

indices_y = np.where(y == most_frequent_value_y)[0]

print("Most frequent value in y:", most_frequent_value_y)
print("Indices of most frequent value in y:", indices_y)

Most frequent value in y: 1
Indices of most frequent value in y: [0 1 2]


In [6]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,1])
print(arr[2,0])

20
70


In [13]:
import numpy as np
Ishita = np.linspace(10, 100, 25)
print("Array:", Ishita)
print("Dimensions of the array:", Ishita.ndim)
print("Shape of the array:", Ishita.shape)
print("Total elements in the array:", Ishita.size)
print("Data type of each element:", Ishita.dtype)
print("Total bytes consumed by the array:", Ishita.nbytes)

transposed_array = Ishita.reshape(25, 1)
print("\nTransposed array using reshape():\n", transposed_array)

transposed_with_T = Ishita.T
print("\nTransposed array using T attribute:\n", transposed_with_T)
print("\nIs transposed_with_T the same as the original array?", np.array_equal(Ishita, transposed_with_T))

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total bytes consumed by the array: 200

Transposed array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Is transposed_with_T the same as the original array? True


In [14]:
import numpy as np
ucs420_Ishita = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,15,20,35]
])

print(np.mean(ucs420_Ishita))
print(np.median(ucs420_Ishita))
print(np.max(ucs420_Ishita))
print(np.min(ucs420_Ishita))
print(np.unique(ucs420_Ishita))

reshaped_ucs420_Ishita = ucs420_Ishita.reshape(4,3)
print(reshaped_ucs420_Ishita)

resized_ucs420_Ishita = np.resize(ucs420_Ishita, (2,3))
print(resized_ucs420_Ishita)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
